obj-m+=demo_drv.o
KERNEL_DIR:=../kernel
CROSS_COMPILE:=../prebuilts/gcc/linux-x86/arm/arm-eabi-4.8/bin/arm-eabi-
PWD:=$(shell pwd)

default:
	$(MAKE) ARCH=arm CROSS_COMPILE=$(CROSS_COMPILE) -C $(KERNEL_DIR) M=$(PWD) modules
	
clean:
	rm  *.o *.order .*.cmd  *.mod.c *.symvers .tmp_versions -rf
